# Generated by Django 3.0.5 on 2020-05-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_panel',
            name='email',
            field=models.CharField(max_length=255, verbose_name='e-mail'),
        ),
    ]
