# Generated by Django 3.0.5 on 2020-05-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200514_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_panel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_panel',
            name='panel_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
