# Generated by Django 3.0.5 on 2020-05-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200514_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_panel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
