# Generated by Django 3.0.5 on 2020-05-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200514_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_panel',
            name='individual',
            field=models.BooleanField(default=True, verbose_name='Частное лицо'),
        ),
    ]
