# Generated by Django 3.0.5 on 2020-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopart', models.CharField(max_length=100)),
                ('autopart_url', models.SlugField(max_length=160, unique=True)),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
