# Generated by Django 3.0.5 on 2020-05-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='autopart_url',
            field=models.SlugField(max_length=160),
        ),
    ]
