# Generated by Django 3.0.5 on 2020-05-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200506_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='указать сумму в рублях', verbose_name='Цена'),
        ),
    ]
