# Generated by Django 3.0.5 on 2020-05-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
